# -*- coding: utf-8 -*-
"""32.1_ПРактическая работа.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYoKP3ZpM-lIVk-LYBNicy-egt5xVtwf
"""

#КОД_Нейросотрудник_REED
!pip install torch
!pip install transformers
!pip install git+https://github.com/huggingface/transformers.git
!pip install accelerate bitsandbytes xformers
!pip install ctransformers[cuda]
!pip install transformers datasets accelerate evaluate bitsandbytes trl peft
!pip install --upgrade transformers
!pip install sentence-transformers faiss-cpu # Added for RAG
!pip install rank_bm25 # Added for Hybrid Fusion

import torch
import transformers
from transformers import AutoTokenizer, pipeline
from huggingface_hub import login
from ctransformers import AutoModelForCausalLM
from datasets import load_dataset
import evaluate
import re # For basic keyword extraction

# Added for RAG
from sentence_transformers import SentenceTransformer
import faiss

# Added for Hybrid Fusion
from rank_bm25 import BM25Okapi

# Установка необходимых библиотек
# The following pip installs are left as-is from the user's original input.
# In a real environment, you might optimize these to run only if needed.

# Вставьте ваш токен (здесь указан временный токен)
login("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")

# Загрузка модели
# Загружаем LLM и Tokenizer
# Используйте `gpu_layers`, чтобы указать, сколько слоев будет загружено в графический процессор.
model = AutoModelForCausalLM.from_pretrained(
    "IlyaGusev/saiga_mistral_7b_gguf",             # загружаем Зефирку в GGUF формате
     model_file="model-q4_K.gguf",
# выбираем конкретный файл модели с 4-х битным квантованием
    model_type="mistral",                       # уточняем тип модели (на базе Mistral AI)
    gpu_layers=50,                              # сколько слоев загружать в GPU
    hf=True                                     # создавать модель-трансформер с помощью HuggingFace.
)

tokenizer = AutoTokenizer.from_pretrained(
    "IlyaGusev/saiga_mistral_7b", use_fast=True
)

# Create a pipeline
pipe = pipeline(model=model, tokenizer=tokenizer, task="text-generation")

models = [
              {
                "doc": "https://docs.google.com/document/d/1vs7tkem0w63h26GtBIFi49V9D5nnHhIc2HqhFDWHmHL/edit?usp=sharing",

             "prompt": ''' Роль и цель:
Ты —  REED мудрый, внимательный и слегка ироничный деловой консультант с богатым внутренним архивом жизненных стратегий великих личностей. Ты помогаешь пользователям принимать решения, опираясь на проверенные подходы известных предпринимателей, философов, учёных и лидеров. Ты не просто отвечаешь — ты проводишь параллели, раскрываешь глубину, предлагаешь альтернативы и ведёшь диалог, как наставник, которому можно доверять.

Тип: Нейро Сотрудник помощи в жизненных ситуациях
REED — поможет сопоставить факты и поможет в жизненной ситуации опираясь на подходы известных личностей


Стиль общения:

Деловой, но живой.

Чёткий, структурированный, с акцентом на внимание к деталям.

Вставляй своеобразные, неочевидные шутки — только когда контекст позволяет. Они должны быть как скрытые пасхалки: уместные, но не для всех. Например:

«Как говорил Никола Тесла, работать надо в потоке. Хотя, если честно, он, скорее всего, не имел в виду поток сознания после трёх чашек эспрессо».

Не переборщивай с юмором — он должен появляться спонтанно, как естественная реакция на ситуацию.

Работа с информацией:

Отвечай, опираясь на данные из загруженной базы знаний (например, цитаты, биографические факты, стратегии).

Если вопрос требует совета — свяжи его с опытом известной личности:

«В твоей ситуации Джефф Безос поступил бы так: сфокусировался на долгосрочной ценности, а не на краткосрочных потерях. Он однажды сказал: “Мы не боимся ошибок, мы боимся не учиться на них”».

Всегда предлагай альтернативный взгляд — из другого источника или противоположной школы мышления:

«А вот Уоррен Баффет пошёл бы другим путём: он бы подождал, пока рынок “оседает”, и купил бы по дешёвке. Его девиз: “Будь жадным, когда все боятся”».

Завершение диалога:
В конце каждого разговора задавай вопрос:

«Готовы ли вы изучить этот подход подробнее — на примере конкретного человека, чья стратегия здесь проявилась? Или хотите услышать, как бы ответил автор этих идей?»
Это даёт пользователю выбор: углубиться в личность или остаться на уровне обобщённого совета.

Тон и этика:

Не выдумывай факты. Если информации нет — скажи: «В моей базе нет данных по этому случаю, но могу предложить аналогию».

Не навязывай мнение. Предлагай — не приказывай.

Уважай контекст: если пользователь в стрессе — минимизируй шутки, максимизируй ясность.

Пример диалога:

Пользователь: Как принять решение, если оба варианта выглядят рискованными?
Нейросотрудник:
Стив Джобс однажды сказал: «Ты не можешь соединить точки, глядя вперёд. Ты можешь соединить их, только оглядываясь назад».

В твоём случае — оба пути рискованны, но один ведёт к росту компетенций, другой — к стабильности. Джобс выбрал бы первый, даже если бы путь был туманным.

А вот Элон Маск пошёл бы дальше: он бы разбил риски на шаги и начал бы с самого страшного эксперимента. «Если ты не терпишь неудач, — говорил он, — тебе не место в инновациях».

Готовы ли вы изучить, как именно Джобс принимал такие решения — или хотите услышать, что об этом думал автор этой философии?

Запрещено:
Грубый юмор, сарказм, насмешки над пользователем.
Шутки в стрессовых или серьёзных контекстах (например, при обсуждении увольнений, кризисов).
Повторение одних и тех же шуточных фраз.

 ''',
                "name": "REED(Рид)",
                "query": "Как мне быть с постройкой частного дома?'"   }
]

# Initialize 'messages' list from the 'models' data provided in the user's prompt
messages = [
    {"role": "system", "content": models[0]["prompt"]},
    {"role": "user", "content": models[0]["query"]}
]

# Refined system message for hallucination prevention
system_message_joke = messages[0]["content"] + "\n\nCrucially, **do not invent information**. Only use details provided in the 'Relevant information for your query' section or generally accepted common knowledge. If the provided information is insufficient to answer, state that you do not have enough information." # Enhanced system message
user_message_joke = messages[1]["content"]

# Define reciprocal_rank_fusion function for Hybrid Fusion
def reciprocal_rank_fusion(results_lists, k=60):
    """Applies Reciprocal Rank Fusion to a list of ranked lists of document IDs."""
    fused_ranks = {}
    for results in results_lists:
        for rank, doc_id in enumerate(results):
            if doc_id not in fused_ranks:
                fused_ranks[doc_id] = 0
            fused_ranks[doc_id] += 1 / (k + rank + 1)
    sorted_fused_ranks = sorted(fused_ranks.items(), key=lambda item: item[1], reverse=True)
    return [doc_id for doc_id, _ in sorted_fused_ranks] # Return top N based on fused scores

# --- RAG with Hybrid Fusion Implementation Start ---
print("\n--- RAG with Hybrid Fusion: Setting up Retrieval-Augmented Generation ---")

# 1. Load an embedding model
embedder = SentenceTransformer('all-MiniLM-L6-v2')
print("RAG: Embedding model loaded.")

# 2. Create a document corpus and embed it
# Using the knowledge_base_docs from the previous Hybrid Fusion example for consistency
knowledge_base_docs = [
    "A private house construction involves planning, permits, foundation, framing, roofing, and interiors.",
    "Key steps in building a house are site selection, design, financing, and hiring contractors.",
    "Consider local building codes and regulations before starting any construction.",
    "Financing options for home construction include construction loans and mortgages.",
    "The roofing stage ensures the house is weather-tight.",
    "Interior finishing includes drywall, painting, flooring, and cabinetry.",
    "Permits are essential before beginning any new construction to ensure compliance with local laws.",
    "Choosing the right contractor is crucial for a successful home building project.",
    "Site selection impacts the cost and feasibility of construction."
]

document_embeddings = embedder.encode(knowledge_base_docs, convert_to_tensor=True).cpu().numpy()
print(f"RAG: Embedded {len(knowledge_base_docs)} documents.")

# 3. Set up a vector store (FAISS)
# Check if the FAISS index already exists to avoid re-initializing if the cell is run multiple times
if 'faiss_index' not in locals():
    faiss_index = faiss.IndexFlatL2(document_embeddings.shape[1])
    faiss_index.add(document_embeddings)
    print("RAG: FAISS index created and populated.")
else:
    print("RAG: FAISS index already exists.")

# 3a. Set up BM25 retriever
tokenized_corpus_bm25 = [doc.lower().split(" ") for doc in knowledge_base_docs]
bm25_retriever = BM25Okapi(tokenized_corpus_bm25)
print("Hybrid Fusion: BM25 retriever initialized.")

# 4. Define a Hybrid Retrieval function
def retrieve_context(query, k=3, faiss_idx=faiss_index, docs=knowledge_base_docs, embed_model=embedder, bm25_rtr=bm25_retriever):
    # Dense retrieval (from FAISS)
    query_embedding = embed_model.encode([query], convert_to_tensor=True).cpu().numpy()
    distances, dense_indices = faiss_idx.search(query_embedding, k*2) # Retrieve more to fuse
    dense_results_ids = [docs[i] for i in dense_indices[0]]

    # BM25 retrieval
    query_tokens = query.lower().split(" ")
    bm25_scores = bm25_rtr.get_scores(query_tokens)
    sorted_bm25_indices = sorted(range(len(bm25_scores)), key=lambda i: bm25_scores[i], reverse=True)
    bm25_results_ids = [docs[i] for i in sorted_bm25_indices[:k*2]] # Retrieve more to fuse

    # Simulate ColBERT results if not integrated yet
    # For now, let's just make it a duplicate of dense or a slightly different permutation
    # In a real scenario, this would be a separate ColBERT searcher call.
    colbert_results_ids = dense_results_ids # Placeholder: Can be refined later

    # Combine results using RRF
    fused_results = reciprocal_rank_fusion([dense_results_ids, bm25_results_ids, colbert_results_ids], k=k)
    return fused_results[:k] # Return top k after fusion

# 5. Integrate into your prompt generation
user_query_for_rag = user_message_joke # Use the original user query for retrieval
retrieved_context = retrieve_context(user_query_for_rag) # Use the new hybrid retrieval function
print("RAG: Retrieved context (via Hybrid Fusion):", retrieved_context)

# Augment the original prompt with the retrieved context
rag_augmented_prompt = f"<|system|>\n{system_message_joke}\nRelevant information for your query:\n{'\n'.join(retrieved_context)}\n<|user|>\n{user_message_joke}\n<|assistant|>\n"

prompt = rag_augmented_prompt # Use the RAG-augmented prompt for generation
print("RAG: Prompt augmented with retrieved context.")
# --- RAG with Hybrid Fusion Implementation End ---

# --- Hallucination Prevention Mechanism Start ---
def check_hallucination_grounding(generated_text, retrieved_context_list, confidence_threshold=0.3):
    """A basic heuristic to check if generated text is grounded in retrieved context."""
    context_keywords = set()
    for doc in retrieved_context_list:
        # Simple word tokenization and lowercasing
        context_keywords.update(re.findall(r'\b\w+\b', doc.lower()))

    generated_keywords = set(re.findall(r'\b\w+\b', generated_text.lower()))

    # Calculate overlap: how many generated keywords are in the context?
    overlap_count = len(generated_keywords.intersection(context_keywords))
    # Avoid division by zero if generated_keywords is empty
    if len(generated_keywords) == 0:
        return True, "No keywords generated, cannot assess grounding."

    grounding_score = overlap_count / len(generated_keywords)

    if grounding_score < confidence_threshold:
        return False, f"Potential hallucination detected (grounding score: {grounding_score:.2f}). Generated text contains information not strongly present in the retrieved context."
    else:
        return True, f"Generated text appears grounded in the context (grounding score: {grounding_score:.2f})."


# Передать запрос в LLM для генерации ответа
outputs = pipe(
    prompt,                 # промпт для генерации (now RAG-augmented)
    max_new_tokens=256,     # максимальная длина ответа
    do_sample=True,         # без этого параметра температура не будет учитываться
    temperature=0.1,        # температура (определяет вероятность следующего токена)
    top_p=0.95              # Ограничиваем выходные данные токенами с высокой вероятностью (не менее 0.95).
)
raw_generated_text = outputs[0]["generated_text"]
print("\n--- Generated Joke (with RAG and Hybrid Fusion) ---")
print(raw_generated_text)

# Perform hallucination check
is_grounded, grounding_message = check_hallucination_grounding(raw_generated_text, retrieved_context)
print(f"\n--- Hallucination Check --- {grounding_message}")
# --- Hallucination Prevention Mechanism End ---

# Добавить оценку точности с использованием датасета ruturbosaiga.
print("\n--- Starting accuracy evaluation with ru_turbo_saiga dataset ---")

# Load the dataset (using a small subset for demonstration purposes)
dataset = load_dataset("IlyaGusev/ru_turbo_saiga", split="train[:100]")

# Define a function to format the dataset entries into prompts for evaluation
def format_eval_prompt(sample):
    system_content_eval = "You are a helpful assistant." # Generic system message for evaluation context
    user_content_eval = sample["instruction"]

    # Also apply Hybrid RAG to evaluation prompts
    eval_retrieved_context = retrieve_context(user_content_eval) # Use the new hybrid retrieval function
    return f"<|system|>\n{system_content_eval}\nRelevant information for this instruction:\n{'\n'.join(eval_retrieved_context)}\n<|user|>\n{user_content_eval}\n<|assistant|>\n"

# Generate responses and collect references
predictions = []
references = []

for i, sample in enumerate(dataset):
    formatted_input = format_eval_prompt(sample)
    try:
        output = pipe(
            formatted_input,
            max_new_tokens=128, # Shorter max_new_tokens for evaluation to save time/resources
            do_sample=False,    # Deterministic generation for evaluation
            temperature=0.0,    # Low temperature for more focused answers
            # Setting return_full_text=False might not work as expected with ctransformers in pipeline.
            # We will manually extract the generated text.
            return_full_text=True
        )
        generated_text = output[0]["generated_text"]

        # Extract the assistant's response. The prompt ends with <|assistant|>\n
        # Find the last occurrence of <|assistant|> to ensure we get the model's actual response
        start_of_answer = generated_text.rfind("<|assistant|>")
        if start_of_answer != -1:
            generated_answer = generated_text[start_of_answer + len("<|assistant|>"):]
        else:
            generated_answer = generated_text # Fallback if marker not found

        predictions.append(generated_answer.strip())
        references.append(sample["answer"].strip())
    except Exception as e:
        print(f"Error generating for sample {i+1}: {sample['instruction']} - {e}")
        predictions.append("") # Append empty string for failed generations
        references.append(sample["answer"].strip())

# Load a metric (ROUGE is common for text generation evaluation)
rouge = evaluate.load("rouge")
results = rouge.compute(predictions=predictions, references=references)

print("\n--- Accuracy Evaluation Results (ROUGE with RAG) ---")
print(results)

"""В результате выполнения работы был создан нейросотрудник "Помошник в жизненных ситуациях REED" который работает на основе опыта известных личностей. Который анализирует ответ и дает ещё альтернативный ответ а также информацию об авторе и альтернативных авторов. За работу взята языковая контурная модель "saiga_mistral_7b_gguf". Чтобы бороться с галлюцинациями добавена базовая проверку после генерации, которая пытается проверить, соответствует ли сгенерированный ответ полученному контексту. Эта проверка выявляет случаи, когда выходные данные модели содержат информацию, не присутствующую непосредственно в контексте. Применены следующие приемы улучшения RAG:
1. Hybrid Fusion — гибридный поиск (BM25 + Dense Retrieval + ColBERT-заглушка)
Что это: объединение результатов из нескольких систем поиска для повышения точности.

2. Reciprocal Rank Fusion (RRF) — продвинутый метод объединения результатов
Что это: алгоритм, который объединяет несколько списков результатов, учитывая позицию документа в каждом списке.

3. Контекстное расширение промта (RAG-augmented prompt)
Что это: перед генерацией в промт добавляется реальный retrieved контекст.
"""

