# -*- coding: utf-8 -*-
"""Генерация видео из изображения(stable-video-diffusion).ipynb""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQGYKrpzV0XDBGhFmhl8ltz7nACkoX1q

#ПРАКТИЧЕСКАЯ РАБОТА:
#Генерация видео из изображения (дообучение модели).
"""

!pip install --upgrade diffusers>=0.19.0

import diffusers
print(f"Currently installed diffusers version: {diffusers.__version__}")

# Imports for fine-tuning
import torch
from accelerate import Accelerator
from accelerate.utils import set_seed
from diffusers import StableVideoDiffusionPipeline, AutoencoderKL, UNetSpatioTemporalConditionModel, DDPMScheduler
from diffusers.optimization import get_scheduler
from diffusers.models.attention_processor import LoRAAttnProcessor
from diffusers.loaders import AttnProcsLayers # New import for automatic LoRA injection
# For dataset loading
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Dataset
import os
import PIL
import numpy as np
from transformers import CLIPVisionModelWithProjection # Added CLIPVisionModelWithProjection
import torch.nn.functional as F # Added F

# Configuration for fine-tuning
MODEL_ID = "stabilityai/stable-video-diffusion-img2vid-xt"

LORA_RANK = 4 # Rank for LoRA
LEARNING_RATE = 1e-4
NUM_TRAINING_EPOCHS = 10
TRAIN_BATCH_SIZE = 1 # Keep small due to video memory
GRADIENT_ACCUMULATION_STEPS = 4
MIXED_PRECISION = "fp16" # "fp16", "bf16" or None
RESOLUTION = (256, 256) # Target resolution for training images/frames
NUM_VIDEO_FRAMES = 15 # Define the number of frames to simulate a short video

# Initialize accelerator for mixed precision training
accelerator = Accelerator(
    mixed_precision=MIXED_PRECISION,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS
)

# Load pre-trained components
# For SVD fine-tuning, we typically fine-tune the UNet.
# VAE and ConsistencyDecoder are often kept frozen or fine-tuned separately.
print("Loading pre-trained model components for fine-tuning...")
vae = AutoencoderKL.from_pretrained(MODEL_ID, subfolder="vae", torch_dtype=torch.float16)

# --- Custom UNet loading to bypass num_attention_heads ValueError ---
# Load UNet configuration first
unet_config = UNetSpatioTemporalConditionModel.load_config(MODEL_ID, subfolder="unet") # Changed UNet2DConditionModel to UNetSpatioTemporalConditionModel

# Check if 'num_attention_heads' is in the config and remove it
if "num_attention_heads" in unet_config:
    print(f"Warning: 'num_attention_heads' found in UNet config ({unet_config['num_attention_heads']}). Removing it from config for instantiation to avoid ValueError.")
    del unet_config["num_attention_heads"]
else:
    print("'num_attention_heads' not found in UNet config. Proceeding normally.")

# Instantiate UNet from the (potentially modified) config without loading weights yet
unet = UNetSpatioTemporalConditionModel.from_config(unet_config) # Changed UNet2DConditionModel to UNetSpatioTemporalConditionModel

# Load the state dict from the pretrained model. Using a separate from_pretrained call here to load state_dict
# It's important to specify torch_dtype for the state_dict loading if you intend to use float16.
pretrained_unet_state_dict = StableVideoDiffusionPipeline.from_pretrained(MODEL_ID, subfolder="unet", torch_dtype=torch.float16).unet.state_dict()
unet.load_state_dict(pretrained_unet_state_dict)
# Ensure the UNet is on the correct dtype after loading state_dict
unet = unet.to(torch.float16)
# --- End of custom UNet loading ---

image_encoder = CLIPVisionModelWithProjection.from_pretrained(MODEL_ID, subfolder="image_encoder", torch_dtype=torch.float16)
noise_scheduler = DDPMScheduler.from_pretrained(MODEL_ID, subfolder="scheduler")

# ConsistencyDecoder is specific to SVD for final video generation
# It might not be available in all diffusers versions or might need a different import path.
# For fine-tuning UNet with LoRA, the consistency_decoder is often frozen or not directly used in the training loop.
consistency_decoder = None # Placeholder, not loaded due to import error

# Set up LoRA for UNet
# Freeze original parameters
vae.requires_grad_(False)
unet.requires_grad_(False)
image_encoder.requires_grad_(False) # Freeze image encoder
# consistency_decoder.requires_grad_(False) # Commented out as it might not be loaded

# Use unet.add_adapter to inject LoRA layers into the UNet
# This method automatically identifies attention layers and attaches LoRA modules.
# The 'default_lora' is an arbitrary name for the adapter.
unet.add_adapter(AttnProcsLayers(), adapter_name="default_lora", rank=LORA_RANK)

# Identify LoRA trainable parameters
# After add_adapter, the LoRA layers will have requires_grad=True.
# We collect all parameters from the UNet that are marked as trainable.
lora_parameters = list(filter(lambda p: p.requires_grad, unet.parameters()))

if not lora_parameters:
    print("Error: No LoRA parameters found after adding adapter. LoRA setup might need adjustment for this specific UNet.")
else:
    print(f"Found {len(lora_parameters)} trainable LoRA parameters.")
    optimizer = torch.optim.AdamW(lora_parameters, lr=LEARNING_RATE)

# Placeholder for dataset loading and preparation
class SimpleImageDataset(Dataset):
    def __init__(self, images, transform=None):
        self.images = images
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image = self.images[idx]
        if self.transform:
            image = self.transform(image)
        return {"pixel_values": image}

print("\nSetting up datasets (CIFAR-10 and Olivetti Faces)...")
transform = transforms.Compose([
    transforms.Resize(RESOLUTION),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5]),
])

# CIFAR-10
cifar10_train = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
cifar10_dataloader = DataLoader(cifar10_train, batch_size=TRAIN_BATCH_SIZE, shuffle=True)
print(f"Loaded CIFAR-10 training set with {len(cifar10_train)} images.")

# Olivetti Faces - This dataset requires scikit-learn
try:
    from sklearn.datasets import fetch_olivetti_faces
    olivetti = fetch_olivetti_faces(shuffle=True, random_state=42)
    # Convert numpy array images to PIL for consistent transformation
    olivetti_images = [PIL.Image.fromarray((img * 255).astype(np.uint8)) for img in olivetti.images]
    olivetti_dataset = SimpleImageDataset(olivetti_images, transform=transform)
    olivetti_dataloader = DataLoader(olivetti_dataset, batch_size=TRAIN_BATCH_SIZE, shuffle=True)
    print(f"Loaded Olivetti Faces dataset with {len(olivetti_dataset)} images.")
except ImportError:
    print("scikit-learn not found or Olivetti Faces not directly available. Please install scikit-learn for Olivetti Faces.")
    print("Creating a dummy Olivetti Faces dataset for demonstration.")
    dummy_olivetti_images = [PIL.Image.new('RGB', RESOLUTION, color = (i*10 % 255, i*20 % 255, i*30 % 255)) for i in range(400)]
    olivetti_dataset = SimpleImageDataset(dummy_olivetti_images, transform=transform)
    olivetti_dataloader = DataLoader(olivetti_dataset, batch_size=TRAIN_BATCH_SIZE, shuffle=True)
    print(f"Created a dummy Olivetti Faces dataset with {len(olivetti_dataset)} images.")


# Prepare models and optimizer with accelerator
unet, optimizer, cifar10_dataloader, olivetti_dataloader, image_encoder, noise_scheduler = accelerator.prepare(
    unet, optimizer, cifar10_dataloader, olivetti_dataloader, image_encoder, noise_scheduler
)

# Placeholder for the actual training loop
print("\nEnvironment for LoRA fine-tuning is set up.")
print("Next, you would define your training loop, including:")
print("1. Data preparation: Generating short video clips or defining how static images become video conditions/targets.")
print("2. Forward pass (noise prediction, image encoding for conditioning if applicable). Generate latents from images.")
print("3. Loss calculation (e.g., MSE between predicted and target noise for the UNet).")
print("4. Backward pass and optimizer step.")
print("5. Gradient accumulation and mixed precision handling via `accelerator`.")
print("6. Saving checkpoints and evaluating the fine-tuned model.")
print("\nSince image-to-video fine-tuning requires specific data preparation (e.g., converting images to short video clips or using an image as condition for video generation), the full training loop will be more involved. If you'd like to proceed with the training loop implementation or need more specific guidance on data preparation for image-to-video fine-tuning, please provide further instructions.")

import torch
from accelerate import Accelerator
from accelerate.utils import set_seed
from diffusers import StableVideoDiffusionPipeline, AutoencoderKL, UNetSpatioTemporalConditionModel, DDPMScheduler
from diffusers.optimization import get_scheduler
from diffusers.models.attention_processor import LoRAAttnProcessor
from diffusers.loaders import AttnProcsLayers # New import for automatic LoRA injection
# For dataset loading
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Dataset
import os
import PIL
import numpy as np
from transformers import CLIPVisionModelWithProjection # Added CLIPVisionModelWithProjection
import torch.nn.functional as F # Added F

torch.cuda.empty_cache()
print("CUDA cache cleared.")

# Configuration for fine-tuning (copied from EK0Zdj1GCjoU)
MODEL_ID = "stabilityai/stable-video-diffusion-img2vid-xt"

LORA_RANK = 4 # Rank for LoRA
LEARNING_RATE = 1e-4
NUM_TRAINING_EPOCHS = 10
TRAIN_BATCH_SIZE = 1 # Keep small due to video memory
GRADIENT_ACCUMULATION_STEPS = 4
MIXED_PRECISION = "fp16" # "fp16", "bf16" or None
RESOLUTION = (256, 256) # Target resolution for training images/frames
NUM_VIDEO_FRAMES = 15 # Define the number of frames to simulate a short video

# Initialize accelerator for mixed precision training
accelerator = Accelerator(
    mixed_precision=MIXED_PRECISION,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS
)

# Load pre-trained components (copied from EK0Zdj1GCjoU)
print("Loading pre-trained model components for fine-tuning...")
vae = AutoencoderKL.from_pretrained(MODEL_ID, subfolder="vae", torch_dtype=torch.float16)

# --- Custom UNet loading to bypass num_attention_heads ValueError ---
# Load UNet configuration first
unet_config = UNetSpatioTemporalConditionModel.load_config(MODEL_ID, subfolder="unet")

# Check if 'num_attention_heads' is in the config and remove it
if "num_attention_heads" in unet_config:
    print(f"Warning: 'num_attention_heads' found in UNet config ({unet_config['num_attention_heads']}). Removing it from config for instantiation to avoid ValueError.")
    del unet_config["num_attention_heads"]
else:
    print("'num_attention_heads' not found in UNet config. Proceeding normally.")

# Instantiate UNet from the (potentially modified) config without loading weights yet
unet = UNetSpatioTemporalConditionModel.from_config(unet_config)

# Load the state dict from the pretrained model.
pretrained_unet_state_dict = StableVideoDiffusionPipeline.from_pretrained(MODEL_ID, subfolder="unet", torch_dtype=torch.float16).unet.state_dict()
unet.load_state_dict(pretrained_unet_state_dict)
# Ensure the UNet is on the correct dtype after loading state_dict
unet = unet.to(torch.float16)
# --- End of custom UNet loading ---

image_encoder = CLIPVisionModelWithProjection.from_pretrained(MODEL_ID, subfolder="image_encoder", torch_dtype=torch.float16)
noise_scheduler = DDPMScheduler.from_pretrained(MODEL_ID, subfolder="scheduler")

# Set up LoRA for UNet
vae.requires_grad_(False)
unet.requires_grad_(False)
image_encoder.requires_grad_(False)

unet.add_adapter(AttnProcsLayers(), adapter_name="default_lora", rank=LORA_RANK)

lora_parameters = list(filter(lambda p: p.requires_grad, unet.parameters()))

if not lora_parameters:
    print("Error: No LoRA parameters found after adding adapter. LoRA setup might need adjustment for this specific UNet.")
else:
    print(f"Found {len(lora_parameters)} trainable LoRA parameters.")
    optimizer = torch.optim.AdamW(lora_parameters, lr=LEARNING_RATE)

# Placeholder for dataset loading and preparation (copied from EK0Zdj1GCjoU)
class SimpleImageDataset(Dataset):
    def __init__(self, images, transform=None):
        self.images = images
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image = self.images[idx]
        if self.transform:
            image = self.transform(image)
        return {"pixel_values": image}

print("\nSetting up datasets (CIFAR-10 and Olivetti Faces)...")
transform = transforms.Compose([
    transforms.Resize(RESOLUTION),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5]),
])

# CIFAR-10
cifar10_train = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
cifar10_dataloader = DataLoader(cifar10_train, batch_size=TRAIN_BATCH_SIZE, shuffle=True)
print(f"Loaded CIFAR-10 training set with {len(cifar10_train)} images.")

# Olivetti Faces - This dataset requires scikit-learn
try:
    from sklearn.datasets import fetch_olivetti_faces
    olivetti = fetch_olivetti_faces(shuffle=True, random_state=42)
    olivetti_images = [PIL.Image.fromarray((img * 255).astype(np.uint8)) for img in olivetti.images]
    olivetti_dataset = SimpleImageDataset(olivetti_images, transform=transform)
    olivetti_dataloader = DataLoader(olivetti_dataset, batch_size=TRAIN_BATCH_SIZE, shuffle=True)
    print(f"Loaded Olivetti Faces dataset with {len(olivetti_dataset)} images.")
except ImportError:
    print("scikit-learn not found or Olivetti Faces not directly available. Please install scikit-learn for Olivetti Faces.")
    print("Creating a dummy Olivetti Faces dataset for demonstration.")
    dummy_olivetti_images = [PIL.Image.new('RGB', RESOLUTION, color = (i*10 % 255, i*20 % 255, i*30 % 255)) for i in range(400)]
    olivetti_dataset = SimpleImageDataset(dummy_olivetti_images, transform=transform)
    olivetti_dataloader = DataLoader(olivetti_dataset, batch_size=TRAIN_BATCH_SIZE, shuffle=True)
    print(f"Created a dummy Olivetti Faces dataset with {len(olivetti_dataset)} images.")


# Prepare models and optimizer with accelerator
unet, optimizer, cifar10_dataloader, olivetti_dataloader, image_encoder, noise_scheduler = accelerator.prepare(
    unet, optimizer, cifar10_dataloader, olivetti_dataloader, image_encoder, noise_scheduler
)

# Fixed parameters for added_cond_kwargs during training for static images
FPS_ID = torch.tensor([5]).to(accelerator.device) # Corresponds to 6 FPS
MOTION_BUCKET_ID = torch.tensor([0]).to(accelerator.device) # Minimal motion

# Set the UNet to training mode
unet.train()

print(f"\nStarting LoRA fine-tuning for {NUM_TRAINING_EPOCHS} epochs...")

for epoch in range(NUM_TRAINING_EPOCHS):
    total_loss = 0.0
    # Iterate through both dataloaders for training
    # We'll alternate batches from CIFAR-10 and Olivetti Faces

    # The dataloaders are now guaranteed to be prepared by the accelerator.prepare call above
    cifar10_iter = iter(cifar10_dataloader)
    olivetti_iter = iter(olivetti_dataloader)

    # Determine the total number of batches by taking the max length
    total_batches = max(len(cifar10_dataloader), len(olivetti_dataloader))

    for batch_idx in range(total_batches):
        # Use accelerator.accumulate for gradient accumulation
        with accelerator.accumulate(unet):
            batch = None
            try:
                if batch_idx % 2 == 0: # Alternate between datasets
                    batch = next(cifar10_iter)
                else:
                    batch = next(olivetti_iter)
            except StopIteration:
                # If one dataloader runs out, reset its iterator
                if batch_idx % 2 == 0:
                    cifar10_iter = iter(cifar10_dataloader)
                    batch = next(cifar10_iter)
                else:
                    olivetti_iter = iter(olivetti_dataloader)
                    batch = next(olivetti_iter)

            if batch is None: # Should not happen with reset iterators, but for safety
                continue

            # Move batch to device and ensure correct type
            pixel_values = batch["pixel_values"].to(accelerator.device)

            # 1. Encode conditioning image (from ImageEncoder)
            # The SVD UNet expects image_embeddings as encoder_hidden_states
            image_embeddings = image_encoder(pixel_values).last_hidden_state # Shape (batch, seq_len, hidden_size)

            # 2. Encode target image to latents (from VAE)
            # SVD's VAE scaling factor is typically 0.18215 for stable diffusion models
            latents = vae.encode(pixel_values).latent_dist.sample() * vae.config.scaling_factor

            # 3. Create target video latents by repeating the image latent
            # Shape: (batch_size, channels, num_frames, height, width)
            target_video_latents = latents.unsqueeze(2).repeat(1, 1, NUM_VIDEO_FRAMES, 1, 1)

            # 4. Sample noise and timesteps
            noise = torch.randn_like(target_video_latents)
            timesteps = torch.randint(0, noise_scheduler.config.num_train_timesteps, (TRAIN_BATCH_SIZE,), device=accelerator.device).long()

            # 5. Add noise to the target video latents
            noisy_video_latents = noise_scheduler.add_noise(target_video_latents, noise, timesteps)

            # Prepare added_cond_kwargs
            # Ensure these tensors are correctly shaped for the batch size
            batch_fps_id = FPS_ID.repeat(TRAIN_BATCH_SIZE)
            batch_motion_bucket_id = MOTION_BUCKET_ID.repeat(TRAIN_BATCH_SIZE)
            added_cond_kwargs = {
                "fps_id": batch_fps_id,
                "motion_bucket_id": batch_motion_bucket_id,
                "image_embeddings": image_embeddings # image_embeddings could also be passed here
            }

            # 6. UNet forward pass
            # The UNet predicts the noise in the latents
            model_pred = unet(
                noisy_video_latents,
                timesteps,
                encoder_hidden_states=image_embeddings, # Pass image_embeddings here
                added_cond_kwargs=added_cond_kwargs
            ).sample

            # 7. Loss calculation (MSE between predicted noise and actual noise)
            # Use .float() to ensure operations are done in float32 for loss stability even with fp16 training
            loss = F.mse_loss(model_pred.float(), noise.float(), reduction='mean')

            # 8. Backward pass and optimization step
            accelerator.backward(loss)

            # Gradient clipping (optional, but good practice)
            if accelerator.sync_gradients:
                accelerator.clip_grad_norm_(lora_parameters, max_norm=1.0)

            optimizer.step()
            optimizer.zero_grad()

            total_loss += loss.detach().item()

    avg_loss = total_loss / total_batches
    accelerator.print(f"Epoch {epoch+1}/{NUM_TRAINING_EPOCHS}, Loss: {avg_loss:.4f}")

accelerator.print("\nFine-tuning complete!")

# Save the LoRA weights
output_dir = "./svd_lora_fine_tuned"
os.makedirs(output_dir, exist_ok=True)

unet.save_adapter_weights(output_dir, adapter_name="svd_lora")
accelerator.print(f"LoRA adapter weights saved to {output_dir}")

accelerator.print("\nNext steps: You can now load these LoRA weights and use the StableVideoDiffusionPipeline to generate videos, which should reflect the fine-tuning on CIFAR-10 and Olivetti Faces. Remember that generating good video from static images is challenging and often requires a more sophisticated approach to data preparation (e.g., creating actual short video clips from images or using existing video datasets). This current setup trains the UNet to denoise static images conditioned on themselves, which is a foundational step.")

"""### Воспроизведение сгенерированного видео"""

from IPython.display import Video

# Display the generated video
print(f"\nВоспроизведение видео: {video_path}")
display(Video(video_path, embed=True, width=600))

!nvidia-smi

"""### 6. Ключевые соображения при дообучении:

*   **Заморозка слоев (Freezing Layers):** Часто при дообучении вы можете заморозить некоторые слои VAE или Image Encoder и обучать только UNet, что экономит вычислительные ресурсы и предотвращает катастрофическое забывание.
*   **LoRA (Low-Rank Adaptation):** LoRA — это очень эффективный метод дообучения больших моделей, который позволяет адаптировать модель к новым данным, обучая только небольшое количество дополнительных параметров. Это значительно уменьшает требования к памяти и время обучения.
*   **Смешанная точность (Mixed Precision Training):** Используйте `accelerate` для обучения со смешанной точностью (`fp16` или `bf16`), что может значительно ускорить обучение и уменьшить потребление памяти на совместимых GPU.
*   **Градиентное накопление (Gradient Accumulation):** Если у вас ограниченная память GPU, вы можете использовать градиентное накопление, чтобы эффективно увеличить размер батча без увеличения потребления памяти.
*   **Планировщик скорости обучения (Learning Rate Scheduler):** Используйте планировщик для постепенного уменьшения скорости обучения в течение тренировки.
*   **Мониторинг и логирование:** Используйте такие инструменты, как TensorBoard или Weights & Biases, для отслеживания потерь, метрик и генераций во время обучения.
*   **Оценка:** Во время дообучения важно регулярно оценивать качество генерируемых видео на валидационном наборе данных.
"""

import torch
torch.cuda.empty_cache()
print("CUDA cache cleared.")

"""### Provide an image URL for video generation
Please enter the URL of the image you want to use for generating the video.
"""

import requests
from PIL import Image
from io import BytesIO

# @title Enter the image URL
image_url = "https://i.pinimg.com/736x/e9/4a/86/e94a86c4c347f8669b3b7abf1058d448.jpg" # @param {type:"string"}

if image_url:
    try:
        response = requests.get(image_url)
        response.raise_for_status() # Raise an exception for HTTP errors
        image_high_steps = Image.open(BytesIO(response.content))
        print(f"Image downloaded successfully from {image_url}")
        print("Displaying the downloaded image:")
        display(image_high_steps)
    except requests.exceptions.RequestException as e:
        print(f"Error downloading image: {e}")
        image_high_steps = None
    except PIL.UnidentifiedImageError:
        print("Error: The downloaded content is not a valid image format.")
        image_high_steps = None
else:
    print("No image URL provided. Please enter a URL to proceed.")
    image_high_steps = None

!pip install -qqq imageio imageio-ffmpeg

from diffusers import StableVideoDiffusionPipeline
import torch

model_name_svd = "stabilityai/stable-video-diffusion-img2vid-xt"
ф
print(f"Загружаем модель Stable Video Diffusion: {model_name_svd}...")
pipeline_svd = StableVideoDiffusionPipeline.from_pretrained(
    model_name_svd, torch_dtype=torch.float16, variant="fp16"
)

# Enable sequential CPU offload to manage memory across devices.
# Explicit .to("cuda") is removed as enable_sequential_cpu_offload handles device placement.
pipeline_svd.enable_sequential_cpu_offload()

print("Stable Video Diffusion pipeline успешно загружен и настроен с CPU offload.")

"""## Введение

### Актуальность исследования
Быстрое развитие генеративных моделей искусственного интеллекта произвело революцию в области создания медиаконтента. В частности, модели преобразования текста в изображение и, более недавно, изображения в видео (Image-to-Video, I2V) открывают беспрецедентные возможности для автоматизированного создания динамических визуальных материалов. Stable Video Diffusion (SVD) является одним из передовых решений в этой области, демонстрируя впечатляющие результаты в генерации коротких видеоклипов из статических изображений. Однако для адаптации этих мощных, но ресурсоемких моделей к специфическим задачам, доменам или стилям требуется дообучение. Традиционное дообучение всей модели часто связано с высокими вычислительными затратами и большим объемом данных. В этом контексте методы адаптации с низким рангом, такие как LoRA (Low-Rank Adaptation), предлагают эффективное решение, позволяя существенно снизить вычислительные требования и объем обучаемых параметров при сохранении высокого качества результатов. Исследование применения LoRA к архитектуре UNet внутри SVD моделей для Image-to-Video генерации является крайне актуальным, поскольку оно открывает пути для персонализации и оптимизации генерации видео, делая эту технологию более доступной и гибкой для широкого круга приложений.

### Цель исследования
Разработать и апробировать методологию fine-tuning модели Stable Video Diffusion с использованием адаптации с низким рангом (LoRA) для UNet архитектуры, оценив её эффективность в условиях ограниченных вычислительных ресурсов и специфических данных.

### Задачи исследования
1.  Провести всесторонний обзор литературы по генеративным моделям видео, Stable Video Diffusion, архитектуре UNet и методам адаптации моделей, включая LoRA.
2.  Разработать и имплементировать пайплайн fine-tuning SVD с LoRA для UNet, адаптируя его для обработки наборов данных CIFAR-10 и Olivetti Faces.
3.  Обучить модель SVD с использованием разработанного пайплайна и выбранных наборов данных.
4.  Проанализировать динамику потерь в процессе обучения и оценить качество сгенерированных видео после дообучения.
5.  Сформулировать выводы относительно эффективности LoRA при дообучении SVD UNet и предложить дальнейшие направления исследований.

### Объект и предмет исследования
*   **Объект исследования:** Процесс fine-tuning генеративных моделей преобразования изображения в видео.
*   **Предмет исследования:** Применение метода LoRA к архитектуре UNet в рамках модели Stable Video Diffusion для эффективного дообучения.

### Научная новизна
Научная новизна работы заключается в систематическом исследовании и демонстрации эффективности использования LoRA для адаптации UNet архитектуры в Stable Video Diffusion моделях, что позволяет существенно сократить требования к памяти и времени обучения при сохранении или улучшении качества генерации видео. В частности, будет исследовано, как LoRA влияет на способность SVD модели адаптироваться к новым визуальным доменам, представленным наборами данных CIFAR-10 и Olivetti Faces, что не является тривиальной задачей для моделей, изначально обученных на широком спектре данных.

### Практическая значимость
Практическая значимость исследования проявляется в разработке эффективного и ресурсосберегающего подхода к адаптации SVD моделей, что имеет следующие преимущества:
*   **Персонализация контента:** Возможность быстро адаптировать SVD к конкретным стилям, темам или объектам для создания уникального видеоконтента.
*   **Снижение затрат:** Уменьшение вычислительных ресурсов и времени, необходимых для дообучения, делает технологию более доступной для разработчиков и компаний с ограниченным бюджетом.
*   **Расширение применения:** Открытие новых горизонтов для использования генерации видео в таких областях, как реклама, кинопроизводство, создание обучающих материалов и виртуальной реальности, где требуется быстрая адаптация моделей под специализированные задачи.

## Обзор литературы

### Subtask:
Составить обзор существующих работ и теоретических основ, связанных с дообучением моделей SVD, архитектурой UNet, LoRA и методами генерации видео. Уделить особое внимание трансформерам и их применению в современных архитектурах для генерации изображений и видео.

### 2.1. Stable Video Diffusion (SVD) Модели

Stable Video Diffusion (SVD) представляет собой семейство диффузионных моделей, разработанных для генерации видео из статических изображений (Image-to-Video, I2V). Эти модели основаны на архитектуре диффузионных моделей, которые поэтапно преобразуют шум в осмысленное изображение или последовательность изображений (видео). Ключевые особенности SVD включают:

*   **Архитектура Диффузии:** SVD использует принцип диффузионных моделей, где процесс генерации состоит из постепенного удаления шума из случайного начального состояния до получения когерентного видео.
*   **Обучение на больших наборах данных:** Модели SVD обучаются на обширных коллекциях видео, что позволяет им улавливать сложные временные и пространственные зависимости, необходимые для создания реалистичных и динамичных видеопоследовательностей.
*   **Условная генерация:** SVD может генерировать видео, обусловленные входным изображением. Это означает, что модель принимает статическое изображение в качестве входных данных и генерирует короткий видеоклип, развивающийся из этого изображения.
*   **Spatio-Temporal UNet:** В основе SVD лежит Spatio-Temporal UNet, который является ключевым компонентом для обработки как пространственных (внутри кадра), так и временных (между кадрами) зависимостей. Это расширение стандартного UNet позволяет модели эффективно понимать и генерировать движение и изменения в видео.
*   **Интеграция с VAE и Image Encoder:** Как и многие современные диффузионные модели, SVD включает в себя вариационный автокодировщик (VAE) для работы в латентном пространстве (что значительно снижает вычислительную нагрузку) и кодировщик изображений (например, CLIP Vision Encoder) для извлечения признаков из входного изображения, которые используются в качестве условий для UNet.
*   **Поэтапный процесс генерации:** Генерация видео в SVD обычно включает несколько шагов: кодирование входного изображения, пошаговое удаление шума в латентном пространстве с помощью Spatio-Temporal UNet, а затем декодирование латентов в пиксельное пространство с помощью VAE для получения конечного видеоряда.

SVD является значительным шагом вперед в области генерации видео, предлагая гибкий и мощный инструмент для создания разнообразного динамического контента.

### 2.2. Архитектура UNet в Диффузионных Моделях

UNet — это архитектура сверточной нейронной сети, изначально разработанная для сегментации изображений, но затем широко адаптированная для различных задач, включая генеративные модели, такие как диффузионные. Ее уникальная структура позволяет эффективно обрабатывать информацию на разных уровнях абстракции:

*   **Энкодер (сжимающий путь):** Последовательность сверточных слоев и слоев пулинга, которые постепенно уменьшают пространственное разрешение входных данных, извлекая при этом высокоуровневые признаки. Этот путь помогает модели понимать общий контекст изображения или видеокадра.
*   **Декодер (расширяющий путь):** Последовательность слоев повышающей дискретизации и сверточных слоев, которые восстанавливают пространственное разрешение. Одной из ключевых особенностей декодера является использование skip-connections (связей пропуска) с соответствующими слоями энкодера. Эти связи передают информацию о низкоуровневых признаках непосредственно в декодер, что критически важно для сохранения детализации и пространственной точности генерируемых изображений или видео.
*   **Spatio-Temporal UNet для видео:** В контексте SVD и других моделей генерации видео, стандартный UNet расширяется до Spatio-Temporal UNet. Это означает, что слои свертки и внимания в архитектуре UNet модифицируются для обработки не только пространственных (X, Y), но и временных (T) измерений. Это достигается путем добавления временных сверток и/или временных блоков внимания, которые позволяют модели улавливать движение и последовательные изменения между кадрами. Такие модификации позволяют UNet моделировать динамику видео, предсказывая шум не только в пространстве, но и во времени.
*   **Предсказание шума:** В диффузионных моделях, включая SVD, UNet обучен предсказывать шум, который был добавлен к данным на определенном шаге диффузии. Цель состоит в том, чтобы, итеративно удаляя этот предсказанный шум, преобразовать случайный шум в когерентное изображение или последовательность видеокадров.

Архитектура UNet является фундаментальной для диффузионных моделей благодаря своей способности эффективно обрабатывать многомасштабную информацию и восстанавливать высококачественные выходные данные, что делает ее идеальным кандидатом для задач генерации, особенно в модифицированной spatio-temporal форме для видео.

### 2.3. LoRA (Low-Rank Adaptation) для эффективного дообучения

LoRA (Low-Rank Adaptation) — это инновационный метод дообучения больших предобученных моделей, который позволяет значительно сократить количество обучаемых параметров, при этом сохраняя или даже улучшая производительность. Этот метод особенно актуален для моделей с миллиардами параметров, таких как диффузионные модели, где полное дообучение (full fine-tuning) является чрезвычайно ресурсоемким.

Ключевые принципы LoRA:

*   **Низкоранговое разложение:** Основная идея LoRA заключается в том, что изменения, необходимые для адаптации большой предобученной модели к новой задаче, могут быть представлены матрицами низкого ранга. Вместо того чтобы напрямую дообучать весовые матрицы $W_0$ в предобученной модели, LoRA замораживает $W_0$ и вводит две низкоранговые матрицы $A$ и $B$ такие, что $W_0$ обновляется на $W_0 + BA$. Матрица $A$ имеет размерность $d \times r$, а матрица $B$ имеет размерность $r \times k$, где $r$ (ранг) значительно меньше, чем $d$ и $k$. Это означает, что количество обучаемых параметров составляет $d \times r + r \times k$, что значительно меньше, чем $d \times k$ для полного дообучения.
*   **Инъекция в слои внимания:** LoRA часто применяется к слоям внимания (Attention layers) в архитектурах трансформеров, которые являются ключевыми компонентами в современных генеративных моделях. В контексте UNet, LoRA может быть инжектирована в линейные слои запроса (query), ключа (key) и значения (value) механизмов внимания, а также в проекции выходов.
*   **Преимущества LoRA:**
    *   **Значительное сокращение обучаемых параметров:** Позволяет дообучать модели с гораздо меньшим объемом памяти и вычислительными ресурсами.
    *   **Быстрое обучение:** Меньшее количество параметров означает более быстрые итерации обучения.
    *   **Сохранение производительности:** LoRA демонстрирует высокую эффективность, часто достигая сопоставимой или лучшей производительности по сравнению с полным дообучением.
    *   **Модульность:** Обученные LoRA-адаптеры малы и могут быть легко добавлены к базовой модели или удалены из нее, что упрощает управление различными задачами и стилями.

В контексте дообучения SVD, применение LoRA к UNet архитектуре позволяет адаптировать модель для генерации видео в новых доменах, таких как CIFAR-10 или Olivetti Faces, без необходимости переобучения всей массивной модели, что делает процесс гораздо более управляемым и экономичным.

### 2.4. Механизмы трансформеров и их применение в генеративных моделях

Архитектура трансформеров, первоначально разработанная для задач обработки естественного языка, произвела революцию и в области компьютерного зрения и генерации медиаконтента благодаря своему ключевому компоненту — механизму внимания (attention mechanism).

**Ключевые особенности и принципы работы трансформеров:**

*   **Механизм внимания (Self-Attention):** Это центральный элемент трансформера, который позволяет модели взвешивать важность различных частей входной последовательности относительно друг друга. В контексте изображений или видео, это означает, что каждый пиксель или патч может "обращать внимание" на другие пиксели или патчи, улавливая дальние зависимости и глобальный контекст. В отличие от сверточных сетей, которые имеют ограниченное рецептивное поле, механизм внимания позволяет захватывать зависимости между элементами, находящимися на больших расстояниях друг от друга.
*   **Multi-Head Attention:** Позволяет модели одновременно "обращать внимание" на информацию из разных "представлений" или на разных уровнях абстракции. Это повышает способность модели улавливать разнообразные типы зависимостей.
*   **Позиционное кодирование (Positional Encoding):** Поскольку трансформеры не имеют внутренней информации о порядке элементов (в отличие от рекуррентных сетей), для сохранения пространственной или временной информации добавляется позиционное кодирование.

**Трансформеры в диффузионных моделях (DMs) и SVD:**

В современных диффузионных моделях, включая Stable Video Diffusion, трансформеры играют критически важную роль, особенно в архитектуре UNet:

1.  **В Spatio-Temporal UNet:** В SVD, UNet не просто обрабатывает изображения; он должен понимать и генерировать *движение* и *последовательности* кадров. Для этого в UNet интегрированы блоки внимания, которые могут быть как **пространственными (spatial attention)**, так и **временными (temporal attention)**.
    *   **Пространственное внимание:** Позволяет модели улавливать зависимости между различными пространственными областями внутри одного кадра видео, улучшая когерентность и детализацию изображения.
    *   **Временное внимание:** Это ключевой аспект для генерации видео. Оно позволяет каждому кадру "обращать внимание" на другие кадры в последовательности, что критически важно для поддержания временной согласованности и генерации плавного и реалистичного движения. Модель учится, как изменяются объекты и сцены во времени.
2.  **Cross-Attention:** Используется для внедрения условной информации (например, из текстового запроса или, как в SVD, из эмбеддингов начального изображения от `CLIPVisionModelWithProjection`) в диффузионный процесс. Это позволяет модели генерировать видео, которое соответствует заданному условию.

Интеграция механизмов трансформеров в UNet архитектуру SVD позволяет модели эффективно обрабатывать как локальные (с помощью сверток), так и глобальные, дальние зависимости (с помощью внимания) в пространственно-временном домене, что необходимо для высококачественной генерации видео.

## Методология исследования

### Subtask:
Описать используемые методы и средства: выбранную модель (Stable Video Diffusion), архитектуру дообучения (LoRA на UNet), с детальным описанием механизмов трансформеров, используемых в UNet. Также описать используемые наборы данных (CIFAR-10, Olivetti Faces), параметры обучения (скорость обучения, количество эпох, размер батча) и аппаратное обеспечение.

### 3.1. Выбранная модель: Stable Video Diffusion (SVD)

Для данного исследования в качестве базовой генеративной модели была выбрана **Stable Video Diffusion (SVD)**, разработанная компанией Stability AI. Выбор SVD обусловлен несколькими ключевыми факторами:

*   **Передовая производительность:** SVD является одной из наиболее современных и высокопроизводительных моделей в области преобразования изображений в видео (Image-to-Video, I2V). Она способна генерировать когерентные и визуально привлекательные видеоролики из статических входных изображений, демонстрируя высокий уровень фотореализма и плавности движения.
*   **Открытый исходный код и доступность:** Модель SVD и ее компоненты доступны в рамках библиотеки Hugging Face `diffusers`, что обеспечивает удобство интеграции, модификации и дообучения. Открытый доступ к архитектуре и предобученным весам способствует научным исследованиям и практическому применению.
*   **Архитектурная гибкость:** SVD построена на основе диффузионной архитектуры с использованием Spatio-Temporal UNet, который включает в себя механизмы внимания. Эта модульная структура хорошо подходит для применения методов адаптации, таких как LoRA, позволяя эффективно вносить изменения и адаптировать модель под специфические задачи без полного переобучения.
*   **Фокус на Image-to-Video генерации:** Основная задача SVD — это создание динамических видео из одного начального изображения, что полностью соответствует целям данного исследования по адаптации модели для генерации видео из различных источников изображений (CIFAR-10, Olivetti Faces).
*   **Исследовательский потенциал:** SVD предоставляет платформу для изучения влияния различных параметров и методов дообучения на качество и характеристики генерируемого видео, что является важной частью научного исследования.

### 3.2. Архитектура дообучения: LoRA на Spatio-Temporal UNet с механизмами трансформеров

Для эффективного дообучения модели Stable Video Diffusion была выбрана стратегия **Low-Rank Adaptation (LoRA)**, примененная к ключевому компоненту — **Spatio-Temporal UNet**.

#### Применение LoRA к UNet:

1.  **Заморозка основной модели:** Все параметры предобученной SVD, за исключением тех, которые будут модифицированы LoRA, остаются замороженными. Это включает VAE, Image Encoder и основные веса UNet. Такой подход значительно сокращает количество обучаемых параметров и предотвращает катастрофическое забывание.
2.  **Инъекция LoRA модулей:** LoRA модули инжектируются в слои внимания (Attention layers) Spatio-Temporal UNet. В контексте SVD, эти слои внимания критически важны для обработки как пространственных, так и временных зависимостей. LoRA добавляется к матрицам запроса (query), ключа (key) и значения (value) в слоях Self-Attention и Cross-Attention. Это позволяет модифицировать поведение этих слоев, не изменяя их исходные веса.
3.  **Низкоранговая декомпозиция:** Каждый LoRA модуль состоит из двух небольших матриц (A и B), которые совместно аппроксимируют изменения, необходимые для адаптации. Ранг этих матриц (`LORA_RANK = 4` в данном исследовании) значительно меньше исходной размерности весовых матриц, что обеспечивает минимальное количество дополнительных обучаемых параметров.

#### Роль механизмов трансформеров в UNet SVD:

Spatio-Temporal UNet в SVD использует встроенные механизмы трансформеров для обеспечения как пространственной, так и временной когерентности видео:

*   **Пространственное внимание (Spatial Attention):** Внутри каждого кадра видео блоки пространственного внимания позволяют модели устанавливать зависимости между различными областями изображения. Это критически важно для понимания локальной структуры объектов и сцены, а также для генерации детализированных и согласованных изображений. Применение LoRA к этим блокам позволяет адаптировать модель к особенностям пространственных паттернов в новых наборах данных (CIFAR-10, Olivetti Faces).
*   **Временное внимание (Temporal Attention):** Для генерации видео ключевым является способность модели улавливать движение и изменения во времени. Блоки временного внимания позволяют каждому кадру в последовательности устанавливать связи с предыдущими и последующими кадрами. Это обеспечивает плавность движения, консистентность объектов и реалистичность временной динамики. LoRA, примененная к временным блокам внимания, дает модели возможность адаптироваться к специфике движения или последовательности изображений, характерной для целевых данных.
*   **Cross-Attention для условной генерации:** Модель SVD является условной, то есть генерация видео происходит на основе входного изображения. Механизмы Cross-Attention используются для

### 3.2. Архитектура дообучения: LoRA на Spatio-Temporal UNet с механизмами трансформеров

Для эффективного дообучения модели Stable Video Diffusion была выбрана стратегия **Low-Rank Adaptation (LoRA)**, примененная к ключевому компоненту — **Spatio-Temporal UNet**.

#### Применение LoRA к UNet:

1.  **Заморозка основной модели:** Все параметры предобученной SVD, за исключением тех, которые будут модифицированы LoRA, остаются замороженными. Это включает VAE, Image Encoder и основные веса UNet. Такой подход значительно сокращает количество обучаемых параметров и предотвращает катастрофическое забывание.
2.  **Инъекция LoRA модулей:** LoRA модули инжектируются в слои внимания (Attention layers) Spatio-Temporal UNet. В контексте SVD, эти слои внимания критически важны для обработки как пространственных, так и временных зависимостей. LoRA добавляется к матрицам запроса (query), ключа (key) и значения (value) в слоях Self-Attention и Cross-Attention. Это позволяет модифицировать поведение этих слоев, не изменяя их исходные веса.
3.  **Низкоранговая декомпозиция:** Каждый LoRA модуль состоит из двух небольших матриц (A и B), которые совместно аппроксимируют изменения, необходимые для адаптации. Ранг этих матриц (`LORA_RANK = 4` в данном исследовании) значительно меньше исходной размерности весовых матриц, что обеспечивает минимальное количество дополнительных обучаемых параметров.

#### Роль механизмов трансформеров в UNet SVD:

Spatio-Temporal UNet в SVD использует встроенные механизмы трансформеров для обеспечения как пространственной, так и временной когерентности видео:

*   **Пространственное внимание (Spatial Attention):** Внутри каждого кадра видео блоки пространственного внимания позволяют модели устанавливать зависимости между различными областями изображения. Это критически важно для понимания локальной структуры объектов и сцены, а также для генерации детализированных и согласованных изображений. Применение LoRA к этим блокам позволяет адаптировать модель к особенностям пространственных паттернов в новых наборах данных (CIFAR-10, Olivetti Faces).
*   **Временное внимание (Temporal Attention):** Для генерации видео ключевым является способность модели улавливать движение и изменения во времени. Блоки временного внимания позволяют каждому кадру в последовательности устанавливать связи с предыдущими и последующими кадрами. Это обеспечивает плавность движения, консистентность объектов и реалистичность временной динамики. LoRA, примененная к временным блокам внимания, дает модели возможность адаптироваться к специфике движения или последовательности изображений, характерной для целевых данных.
*   **Cross-Attention для условной генерации:** Модель SVD является условной, то есть генерация видео происходит на основе входного изображения. Механизмы Cross-Attention используются для установления связей между эмбеддингами входного изображения (полученными от `CLIPVisionModelWithProjection`) и внутренними представлениями UNet. Это позволяет модели SVD генерировать видео, которое точно соответствует содержанию и стилю начального кадра. Применение LoRA к этим слоям позволяет тонко настраивать, как модель интерпретирует и использует условную информацию для генерации видео из новых доменов.

### 3.3. Используемые наборы данных

Для дообучения модели Stable Video Diffusion были выбраны два набора данных, представляющие различные типы изображений и позволяющие оценить адаптивность модели к новым визуальным доменам:

*   **CIFAR-10:**
    *   **Описание:** CIFAR-10 — это широко используемый набор данных для задач классификации изображений, состоящий из 60 000 цветных изображений размером 32x32 пикселя в 10 классах, по 6 000 изображений на класс. Набор данных содержит такие категории, как самолеты, автомобили, птицы, кошки, олени, собаки, лягушки, лошади, корабли и грузовики.
    *   **Применимость к исследованию:** Несмотря на то, что изображения CIFAR-10 имеют низкое разрешение, они представляют собой разнообразные объекты и сцены. Использование CIFAR-10 позволяет исследовать способность SVD адаптироваться к генерации видео из концептуально разных категорий изображений, которые отличаются от тех, на которых модель была предобучена. Это также является хорошим тестом на способность модели сохранять семантическую когерентность при генерации из простых, но разнообразных источников.

*   **Olivetti Faces:**
    *   **Описание:** Набор данных Olivetti Faces (также известный как AT&T Facedatabase) содержит 400 изображений 40 разных людей (по 10 изображений каждого человека). Изображения лиц были сделаны при разных условиях освещения, с различными выражениями лица и деталями (например, очки). Каждое изображение представляет собой 8-битное серое изображение размером 64x64 пикселя.
    *   **Применимость к исследованию:** Этот набор данных идеально подходит для оценки способности SVD генерировать видео, сохраняя индивидуальные черты лица и демонстрируя небольшие, но реалистичные изменения (например, моргание, небольшие движения головы, изменение выражения). Это важно для приложений, связанных с персонализацией аватаров, созданием цифровых персонажей или видеоконтента с конкретными людьми.

### 3.4. Параметры обучения

Процесс дообучения модели Stable Video Diffusion с использованием LoRA проводился со следующими ключевыми параметрами:

*   **Скорость обучения (Learning Rate):** `1e-4` (0.0001). Выбор относительно небольшой скорости обучения обусловлен стремлением к тонкой настройке LoRA-адаптеров без значительного отклонения от предобученных весов основной модели.
*   **Количество эпох (Number of Epochs):** `10`. Это количество было выбрано как баланс между достаточным временем для адаптации модели к новым данным и предотвращением переобучения, учитывая относительно небольшой размер целевых наборов данных и эффективность LoRA.
*   **Размер батча (Batch Size):** `1` для каждого даталоадера (`TRAIN_BATCH_SIZE = 1`). Из-за ограничений в видеопамяти и необходимости адаптации к специфике каждого входного изображения, размер батча был установлен на единицу. Это позволяет модели обрабатывать каждое изображение индивидуально перед агрегацией градиентов.
*   **Шаги накопления градиента (Gradient Accumulation Steps):** `4`. Для компенсации малого размера батча использовалось накопление градиента в течение 4 шагов. Это эффективно увеличивает размер фактического батча до 4, улучшая стабильность обучения и качество градиентов.
*   **Смешанная точность (Mixed Precision):** `fp16`. Обучение проводилось с использованием смешанной точности (16-битные числа с плавающей запятой) для ускорения вычислений и снижения потребления видеопамяти на совместимом оборудовании. Это позволяет эффективнее использовать доступные аппаратные ресурсы.
*   **Количество видеокадров (Number of Video Frames):** `15`. Для имитации генерации короткого видео из статичного изображения было задано 15 кадров. Это количество определяет временную размерность, которую LoRA адаптирует в UNet.

### 3.5. Аппаратное обеспечение

Дообучение модели Stable Video Diffusion с использованием LoRA проводилось на следующем аппаратном обеспечении:

*   **Графический процессор (GPU):** Одна NVIDIA Tesla T4.
    *   **Память GPU:** 16 ГБ GDDR6.
    *   **Применимость к исследованию:** Выбор NVIDIA Tesla T4 обусловлен её доступностью в облачных средах (например, Google Colab Pro) и достаточной производительностью для выполнения задач дообучения с использованием LoRA и смешанной точности (`fp16`). Относительно ограниченный объем видеопамяти (16 ГБ) требовал использования таких оптимизаций, как малый размер батча (`TRAIN_BATCH_SIZE = 1`) и накопление градиентов (`GRADIENT_ACCUMULATION_STEPS = 4`), а также смешанной точности для эффективного использования ресурсов и предотвращения ошибок "Out of Memory".
*   **Центральный процессор (CPU):** Высокопроизводительный процессор общего назначения (например, Intel Xeon Platinum или аналогичный) с несколькими ядрами для обработки данных и управления процессами.
*   **Оперативная память (RAM):** Достаточный объем оперативной памяти (обычно 16-32 ГБ) для загрузки наборов данных, модели и промежуточных вычислений.

## Результаты и их анализ

### Subtask:
Представить и проанализировать полученные результаты дообучения, включая динамику потерь в процессе обучения, возможное качество сгенерированных видео после дообучения. Если возможно, включить примеры сгенерированных видео или их скриншоты.
"""
