# -*- coding: utf-8 -*-
"""Практическая работа №_1..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120Ykl-DIc8wtRk0TSDa3WwnU8S5RgCRx

Практическая работа №1.
"""

#Задача_№_1_Обнаружение фальшивых новостей
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

df = pd.read_csv('fake_news.csv')
df.head()
df.info()
df.duplicated().sum()
df.drop(columns=['Unnamed: 0', 'title'], inplace=True)
df
df.label.value_counts()
plt.bar(df.label.value_counts().index, df.label.value_counts());


RANDOM_STATE = 15
X_train, X_test, y_train, y_test = (
train_test_split(df['text'], df['label'], test_size=0.25, stratify=df['label'], random_state=RANDOM_STATE))
pipe = Pipeline([('vct', TfidfVectorizer(stop_words='english', min_df=1e-5)),
('clf', PassiveAggressiveClassifier(random_state = RANDOM_STATE))
])
pipe.fit(X_train, y_train)
#Оценка модели
pipe.score(X_train, y_train)
#то же самое-оценка модели
accuracy_score(y_train, pipe.predict(X_train))
pipe.score(X_test, y_test)
#Построение матрицы ошибок
cm = confusion_matrix(y_test, pipe.predict(X_test), labels=pipe.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
display_labels=pipe.classes_)

disp.plot()
plt.show()

#Задача 2. Обнаружение болезни паркинсона с помощью XGBoost
from re import X
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
df = pd.read_table('https://storage.yandexcloud.net/academy.ai/practica/parkinsons.data', sep=',')
df.head()
#Получить основную информацию
df.info()
#Дубликаты в наборе данных
df.duplicated()
#Чистота встречаемости данных
df.status.value_counts()
#Раздел входные и выходные данные
X = df.drop(columns=['name','status'])
y = df.status
X_tr, X_test, y_tr, y_test = train_test_split(X, y, test_size=0.2, random_state=6, stratify=y)
#Вызваем класс
from xgboost import XGBClassifier
clf = XGBClassifier()
clf.fit(X_tr, y_tr)
#Проверим точность классификации на обучающем множестве
clf.score(X_tr, y_tr)
#Проверим точность классификации на тестовом множестве
clf.score(X_test, y_test)
#Строим матрицу ошибок
cm = confusion_matrix(y_test, clf.predict(X_test), labels=clf.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
display_labels=clf.classes_)

disp.plot()
plt.show()
#дополнительные метрики
from sklearn.metrics import precision_score, recall_score, f1_score
precision_score(y_test, clf.predict(X_test))

recall_score(y_test, clf.predict(X_test))

f1_score(y_test, clf.predict(X_test))

"""#Задача №3
Классификатор: "Собака/Человек"
Синтетические данные: Создана синтетическая выборка из 1000 образцов (800 для обучения, 200 для тестирования).
Модель Random Forest (одиночная оценка):
Точность на обучающей выборке: 100.00%
ROC-AUC на обучающей выборке: 100.00%
Точность на тестовой выборке: 89.00%
ROC-AUC на тестовой выборке: 96.18%
Матрица ошибок показывает 83 правильных предсказания для класса 0 (вероятно, "собака") и 95 для класса 1 (вероятно, "человек") на тестовой выборке.
Кросс-валидация Random Forest: Средняя точность составила 88.20% (±1.81%) по 5 фолдам.
Сравнение моделей: Проведено сравнение нескольких моделей (Random Forest, SVM, Gradient Boosting, KNN, Logistic Regression) с оптимизацией гиперпараметров и кросс-валидацией.
Модель SVM показала наилучшую тестовую точность в 91.00% и ROC-AUC в 97.38%.
KNN показал хорошие результаты с точностью 90.50% и самым быстрым временем обучения.
"""

#_Задача_№_3.
#Пробная, приблизительная модель с набором данных, которые должны быть.

#модель классического машинного обучения, которая может с высокой точностью более 90% определять кто перед нами собака или человек

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow_datasets as tfds
import tensorflow as tf
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# Для работы с изображениями (в реальном проекте)
from PIL import Image
import cv2
import os

# ML библиотеки
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, roc_auc_score, roc_curve
)
from sklearn.pipeline import Pipeline

# Для синтетических данных
from sklearn.datasets import make_classification

# Для визуализации
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

class DogHumanClassifier:
    """
    Классификатор для определения собаки или человека на изображении
    """

    def __init__(self, model_type='random_forest', use_pca=True):
        """
        Инициализация классификатора

        Parameters:
        -----------
        model_type : str
            Тип модели: 'random_forest', 'svm', 'gradient_boosting', 'knn', 'logistic'
        use_pca : bool
            Использовать PCA для уменьшения размерности
        """
        self.model_type = model_type
        self.use_pca = use_pca
        self.scaler = StandardScaler()
        self.label_encoder = LabelEncoder()

        # Инициализация PCA
        if use_pca:
            self.pca = PCA(n_components=0.95, random_state=42)

        # Инициализация модели
        if model_type == 'random_forest':
            self.model = RandomForestClassifier(
                n_estimators=200,
                max_depth=20,
                min_samples_split=5,
                min_samples_leaf=2,
                random_state=42,
                n_jobs=-1,
                class_weight='balanced'
            )
        elif model_type == 'svm':
            self.model = SVC(
                C=1.0,
                kernel='rbf',
                gamma='scale',
                probability=True,
                random_state=42,
                class_weight='balanced'
            )
        elif model_type == 'gradient_boosting':
            self.model = GradientBoostingClassifier(
                n_estimators=150,
                learning_rate=0.1,
                max_depth=5,
                random_state=42,
                subsample=0.8
            )
        elif model_type == 'knn':
            self.model = KNeighborsClassifier(
                n_neighbors=5,
                weights='uniform',
                metric='minkowski',
                p=2
            )
        elif model_type == 'logistic':
            self.model = LogisticRegression(
                max_iter=1000,
                C=1.0,
                random_state=42,
                class_weight='balanced',
                solver='liblinear'
            )
        else:
            raise ValueError(f"Неизвестный тип модели: {model_type}")

        # История обучения
        self.training_history = {
            'accuracy': None,
            'roc_auc': None,
            'best_params': None,
            'feature_importance': None,
            'training_time': None
        }

        # Признаки для извлечения (в реальном проекте)
        self.feature_names = [
            'aspect_ratio', 'area_ratio', 'compactness',
            'circularity', 'solidity', 'convexity',
            'hu_moment_1', 'hu_moment_2', 'hu_moment_3',
            'hu_moment_4', 'hu_moment_5', 'hu_moment_6', 'hu_moment_7',
            'color_mean_r', 'color_mean_g', 'color_mean_b',
            'color_std_r', 'color_std_g', 'color_std_b',
            'edge_density', 'texture_energy', 'texture_contrast',
            'texture_homogeneity', 'texture_correlation',
            'symmetry_score', 'centroid_x', 'centroid_y',
            'eccentricity', 'orientation'
        ]

    def extract_features_from_image(self, image_path):
        """
        Извлечение признаков из изображения (реальный метод)

        Parameters:
        -----------
        image_path : str
            Путь к изображению

        Returns:
        --------
        np.array : вектор признаков
        """
        # В реальном проекте здесь будет код для обработки изображений
        # Для демонстрации возвращаем случайные признаки

        np.random.seed(hash(image_path) % 2**32)

        # Генерация реалистичных признаков для собак и людей
        if 'dog' in image_path.lower():
            # Признаки для собак
            features = np.array([
                np.random.uniform(1.2, 1.8),    # aspect_ratio
                np.random.uniform(0.3, 0.6),    # area_ratio
                np.random.uniform(0.7, 0.9),    # compactness
                np.random.uniform(0.4, 0.7),    # circularity
                np.random.uniform(0.85, 0.95),  # solidity
                np.random.uniform(0.9, 0.98),   # convexity
                np.random.normal(0.15, 0.02),   # hu_moment_1
                np.random.normal(0.08, 0.01),   # hu_moment_2
                np.random.normal(0.05, 0.005),  # hu_moment_3
                np.random.normal(0.03, 0.003),  # hu_moment_4
                np.random.normal(0.02, 0.002),  # hu_moment_5
                np.random.normal(0.01, 0.001),  # hu_moment_6
                np.random.normal(0.005, 0.0005),# hu_moment_7
                np.random.uniform(80, 120),     # color_mean_r
                np.random.uniform(60, 100),     # color_mean_g
                np.random.uniform(40, 80),      # color_mean_b
                np.random.uniform(20, 40),      # color_std_r
                np.random.uniform(15, 30),      # color_std_g
                np.random.uniform(10, 25),      # color_std_b
                np.random.uniform(0.1, 0.3),    # edge_density
                np.random.uniform(0.2, 0.4),    # texture_energy
                np.random.uniform(0.3, 0.6),    # texture_contrast
                np.random.uniform(0.4, 0.7),    # texture_homogeneity
                np.random.uniform(0.5, 0.8),    # texture_correlation
                np.random.uniform(0.6, 0.9),    # symmetry_score
                np.random.uniform(0.4, 0.6),    # centroid_x
                np.random.uniform(0.4, 0.6),    # centroid_y
                np.random.uniform(0.7, 0.9),    # eccentricity
                np.random.uniform(-45, 45)      # orientation
            ])
        else:
            # Признаки для людей
            features = np.array([
                np.random.uniform(0.5, 1.2),    # aspect_ratio
                np.random.uniform(0.1, 0.4),    # area_ratio
                np.random.uniform(0.5, 0.8),    # compactness
                np.random.uniform(0.2, 0.5),    # circularity
                np.random.uniform(0.75, 0.9),   # solidity
                np.random.uniform(0.85, 0.95),  # convexity
                np.random.normal(0.25, 0.03),   # hu_moment_1
                np.random.normal(0.12, 0.02),   # hu_moment_2
                np.random.normal(0.08, 0.01),   # hu_moment_3
                np.random.normal(0.05, 0.005),  # hu_moment_4
                np.random.normal(0.03, 0.003),  # hu_moment_5
                np.random.normal(0.02, 0.002),  # hu_moment_6
                np.random.normal(0.01, 0.001),  # hu_moment_7
                np.random.uniform(100, 150),    # color_mean_r
                np.random.uniform(80, 120),     # color_mean_g
                np.random.uniform(60, 100),     # color_mean_b
                np.random.uniform(25, 45),      # color_std_r
                np.random.uniform(20, 35),      # color_std_g
                np.random.uniform(15, 30),      # color_std_b
                np.random.uniform(0.05, 0.2),   # edge_density
                np.random.uniform(0.1, 0.3),    # texture_energy
                np.random.uniform(0.2, 0.5),    # texture_contrast
                np.random.uniform(0.3, 0.6),    # texture_homogeneity
                np.random.uniform(0.4, 0.7),    # texture_correlation
                np.random.uniform(0.7, 0.95),   # symmetry_score
                np.random.uniform(0.45, 0.55),  # centroid_x
                np.random.uniform(0.45, 0.55),  # centroid_y
                np.random.uniform(0.5, 0.8),    # eccentricity
                np.random.uniform(-30, 30)      # orientation
            ])

        return features


    def train(self, X_train, y_train, optimize_hyperparams=True):
        """
        Обучение модели

        Parameters:
        -----------
        X_train : np.array
            Обучающие данные
        y_train : np.array
            Метки классов
        optimize_hyperparams : bool
            Оптимизировать гиперпараметры

        Returns:
        --------
        self : обученная модель
        """
        import time
        start_time = time.time()

        print(f"\nОбучение модели {self.model_type.upper()}...")

        # Масштабирование признаков
        print("Масштабирование признаков...")
        X_scaled = self.scaler.fit_transform(X_train)

        # Применение PCA
        if self.use_pca:
            print("Применение PCA...")
            X_processed = self.pca.fit_transform(X_scaled)
            print(f"  Исходная размерность: {X_scaled.shape[1]}")
            print(f"  После PCA: {X_processed.shape[1]} компонент")
            print(f"  Объясненная дисперсия: {self.pca.explained_variance_ratio_.sum():.2%}")
        else:
            X_processed = X_scaled

        # Оптимизация гиперпараметров
        if optimize_hyperparams:
            print("Оптимизация гиперпараметров...")
            best_params = self._optimize_hyperparameters(X_processed, y_train)
            self.training_history['best_params'] = best_params

        # Обучение модели
        print("Обучение финальной модели...")
        self.model.fit(X_processed, y_train)

        # Оценка на обучающей выборке
        train_pred = self.model.predict(X_processed)
        train_accuracy = accuracy_score(y_train, train_pred)

        # Расчет ROC-AUC если возможно
        if hasattr(self.model, 'predict_proba'):
            train_proba = self.model.predict_proba(X_processed)[:, 1]
            train_roc_auc = roc_auc_score(y_train, train_proba)
        else:
            train_roc_auc = None

        # Сохранение истории
        training_time = time.time() - start_time
        self.training_history.update({
            'accuracy': train_accuracy,
            'roc_auc': train_roc_auc,
            'training_time': training_time,
            'n_features': X_processed.shape[1],
            'n_samples': len(X_train)
        })

        # Извлечение важности признаков
        if hasattr(self.model, 'feature_importances_'):
            if self.use_pca:
                # Для PCA преобразуем важность обратно в исходное пространство
                pca_importance = self.model.feature_importances_
                original_importance = np.abs(self.pca.components_.T @ pca_importance)
                self.training_history['feature_importance'] = dict(
                    zip(self.feature_names, original_importance)
                )
            else:
                self.training_history['feature_importance'] = dict(
                    zip(self.feature_names, self.model.feature_importances_)
                )

        print(f"\nОбучение завершено за {training_time:.2f} секунд")
        print(f"Точность на обучающей выборке: {train_accuracy:.2%}")
        if train_roc_auc:
            print(f"ROC-AUC на обучающей выборке: {train_roc_auc:.2%}")

        return self

    def _optimize_hyperparameters(self, X, y):
        """
        Оптимизация гиперпараметров модели

        Parameters:
        -----------
        X : np.array
            Данные
        y : np.array
            Метки

        Returns:
        --------
        dict : лучшие параметры
        """
        param_grids = {
            'random_forest': {
                'n_estimators': [100, 200, 300],
                'max_depth': [10, 20, 30, None],
                'min_samples_split': [2, 5, 10],
                'min_samples_leaf': [1, 2, 4]
            },
            'svm': {
                'C': [0.1, 1, 10, 100],
                'gamma': ['scale', 'auto', 0.01, 0.1, 1],
                'kernel': ['rbf', 'poly', 'sigmoid']
            },
            'gradient_boosting': {
                'n_estimators': [50, 100, 150],
                'learning_rate': [0.01, 0.1, 0.2],
                'max_depth': [3, 5, 7],
                'subsample': [0.8, 0.9, 1.0]
            },
            'knn': {
                'n_neighbors': [3, 5, 7, 9, 11],
                'weights': ['uniform', 'distance'],
                'metric': ['euclidean', 'manhattan', 'minkowski']
            },
            'logistic': {
                'C': [0.01, 0.1, 1, 10, 100],
                'penalty': ['l1', 'l2'],
                'solver': ['liblinear', 'saga']
            }
        }

        if self.model_type not in param_grids:
            return None

        print(f"  Поиск по сетке для {self.model_type}...")
        grid_search = GridSearchCV(
            self.model,
            param_grids[self.model_type],
            cv=5,
            scoring='accuracy',
            n_jobs=-1,
            verbose=0
        )

        grid_search.fit(X, y)

        print(f"  Лучшие параметры: {grid_search.best_params_}")
        print(f"  Лучшая точность: {grid_search.best_score_:.2%}")

        # Обновляем модель с лучшими параметрами
        self.model = grid_search.best_estimator_

        return grid_search.best_params_

    def predict(self, X, return_proba=True):
        """
        Предсказание для новых данных

        Parameters:
        -----------
        X : np.array
            Данные для предсказания
        return_proba : bool
            Возвращать вероятности

        Returns:
        --------
        tuple : (predictions, confidences)
        """
        # Масштабирование
        X_scaled = self.scaler.transform(X)

        # PCA
        if self.use_pca:
            X_processed = self.pca.transform(X_scaled)
        else:
            X_processed = X_scaled

        # Предсказание
        predictions = self.model.predict(X_processed)

        # Уверенность/вероятности
        if return_proba and hasattr(self.model, 'predict_proba'):
            probabilities = self.model.predict_proba(X_processed)
            confidences = np.max(probabilities, axis=1)
        else:
            if hasattr(self.model, 'decision_function'):
                distances = self.model.decision_function(X_processed)
                confidences = 1 / (1 + np.exp(-np.abs(distances)))
            else:
                confidences = np.ones_like(predictions) * 0.8

        return predictions, confidences

    def evaluate(self, X_test, y_test, verbose=True):
        """
        Полная оценка модели

        Parameters:
        -----------
        X_test : np.array
            Тестовые данные
        y_test : np.array
            Истинные метки

        Returns:
        --------
        dict : результаты оценки
        """
        if verbose:
            print("\n" + "="*60)
            print(f"ОЦЕНКА МОДЕЛИ {self.model_type.upper()}")
            print("="*60)

        # Предсказание
        predictions, confidences = self.predict(X_test)

        # Расчет метрик
        accuracy = accuracy_score(y_test, predictions)
        report = classification_report(y_test, predictions, output_dict=True)
        cm = confusion_matrix(y_test, predictions)

        # ROC-AUC
        if hasattr(self.model, 'predict_proba'):
            probabilities = self.model.predict_proba(
                self.pca.transform(self.scaler.transform(X_test))
                if self.use_pca else self.scaler.transform(X_test)
            )[:, 1]
            roc_auc = roc_auc_score(y_test, probabilities)
            fpr, tpr, _ = roc_curve(y_test, probabilities)
        else:
            roc_auc = None
            fpr = tpr = None

        if verbose:
            print(f"\nТочность: {accuracy:.2%}")
            if roc_auc:
                print(f"ROC-AUC: {roc_auc:.2%}")

            print("\nОтчет классификации:")
            print(classification_report(y_test, predictions))

            print("\nМатрица ошибок:")
            print(cm)

        # Сохранение результатов
        evaluation_results = {
            'accuracy': accuracy,
            'roc_auc': roc_auc,
            'classification_report': report,
            'confusion_matrix': cm.tolist(),
            'fpr': fpr.tolist() if fpr is not None else None,
            'tpr': tpr.tolist() if tpr is not None else None,
            'predictions': predictions.tolist(),
            'confidences': confidences.tolist()
        }

        return evaluation_results

    def cross_validate(self, X, y, cv=5):
        """
        Кросс-валидация модели

        Parameters:
        -----------
        X : np.array
            Все данные
        y : np.array
            Все метки
        cv : int
            Количество фолдов

        Returns:
        --------
        dict : результаты кросс-валидации
        """
        print(f"\nКросс-валидация ({cv} фолдов)...")

        # Создание пайплайна
        pipeline_steps = [('scaler', self.scaler)]
        if self.use_pca:
            pipeline_steps.append(('pca', self.pca))
        pipeline_steps.append(('classifier', self.model))

        pipeline = Pipeline(pipeline_steps)

        # Кросс-валидация
        cv_scores = cross_val_score(
            pipeline, X, y,
            cv=cv,
            scoring='accuracy',
            n_jobs=-1
        )

        print(f"Результаты кросс-валидации:")
        for i, score in enumerate(cv_scores, 1):
            print(f"  Фолд {i}: {score:.2%}")

        print(f"\nСредняя точность: {cv_scores.mean():.2%} (±{cv_scores.std():.2%})")

        return {
            'cv_scores': cv_scores.tolist(),
            'mean_accuracy': cv_scores.mean(),
            'std_accuracy': cv_scores.std(),
            'cv_folds': cv
        }

    def visualize_results(self, X_test, y_test, evaluation_results):
        """
        Визуализация результатов

        Parameters:
        -----------
        X_test : np.array
            Тестовые данные
        y_test : np.array
            Истинные метки
        evaluation_results : dict
            Результаты оценки
        """
        import plotly.graph_objects as go
        from plotly.subplots import make_subplots

        # Создание фигуры с несколькими графиками
        fig = make_subplots(
            rows=2, cols=2,
            subplot_titles=(
                'Матрица ошибок',
                'ROC-кривая' if evaluation_results['roc_auc'] else 'Распределение уверенности',
                'Важность признаков',
                'Сравнение предсказаний'
            ),
            specs=[
                [{'type': 'heatmap'}, {'type': 'scatter'}],
                [{'type': 'bar'}, {'type': 'scatter'}]
            ]
        )

        # 1. Матрица ошибок
        cm = np.array(evaluation_results['confusion_matrix'])
        fig.add_trace(
            go.Heatmap(
                z=cm,
                x=['Собака', 'Человек'],
                y=['Собака', 'Человек'],
                text=cm,
                texttemplate='%{text}',
                textfont={"size": 16},
                colorscale='Blues',
                showscale=True
            ),
            row=1, col=1
        )

        # 2. ROC-кривая или распределение уверенности
        if evaluation_results['roc_auc']:
            fig.add_trace(
                go.Scatter(
                    x=evaluation_results['fpr'],
                    y=evaluation_results['tpr'],
                    mode='lines',
                    name=f'ROC (AUC = {evaluation_results["roc_auc"]:.3f})',
                    line=dict(color='royalblue', width=3)
                ),
                row=1, col=2
            )
            fig.add_trace(
                go.Scatter(
                    x=[0, 1], y=[0, 1],
                    mode='lines',
                    name='Случайный классификатор',
                    line=dict(color='gray', width=2, dash='dash')
                ),
                row=1, col=2
            )
            fig.update_xaxes(title_text='False Positive Rate', row=1, col=2)
            fig.update_yaxes(title_text='True Positive Rate', row=1, col=2)
        else:
            # Распределение уверенности
            confidences = evaluation_results['confidences']
            fig.add_trace(
                go.Histogram(
                    x=confidences,
                    nbinsx=20,
                    name='Уверенность предсказаний',
                    marker_color='lightseagreen'
                ),
                row=1, col=2
            )
            fig.update_xaxes(title_text='Уверенность', row=1, col=2)
            fig.update_yaxes(title_text='Частота', row=1, col=2)

        # 3. Важность признаков (если есть)
        if self.training_history.get('feature_importance'):
            importance = self.training_history['feature_importance']
            top_features = dict(sorted(importance.items(), key=lambda x: x[1], reverse=True)[:15])

            fig.add_trace(
                go.Bar(
                    x=list(top_features.values()),
                    y=list(top_features.keys()),
                    orientation='h',
                    name='Важность признаков',
                    marker_color='coral'
                ),
                row=2, col=1
            )
            fig.update_xaxes(title_text='Важность', row=2, col=1)

        # 4. Сравнение предсказаний
        predictions = evaluation_results['predictions']
        correct = (predictions == y_test).astype(int)

        fig.add_trace(
            go.Scatter(
                x=list(range(len(predictions))),
                y=predictions,
                mode='markers',
                name='Предсказания',
                marker=dict(
                    size=10,
                    color=correct,
                    colorscale=['red', 'green'],
                    showscale=True,
                    colorbar=dict(title="Правильно")
                )
            ),
            row=2, col=2
        )
        fig.add_trace(
            go.Scatter(
                x=list(range(len(y_test))),
                y=y_test,
                mode='markers',
                name='Истинные значения',
                marker=dict(symbol='x', size=8, color='black')
            ),
            row=2, col=2
        )
        fig.update_xaxes(title_text='Образец', row=2, col=2)
        fig.update_yaxes(title_text='Класс (0=Собака, 1=Человек)', row=2, col=2)

        # Обновление layout
        fig.update_layout(
            height=800,
            width=1200,
            title_text=f'Результаты классификации: {self.model_type.upper()}',
            showlegend=True,
            template='plotly_white'
        )

        return fig

    def save_model(self, filename='dog_human_classifier.pkl'):
        """
        Сохранение модели
        """
        import pickle
        import json
        from datetime import datetime

        model_data = {
            'model': self.model,
            'scaler': self.scaler,
            'pca': self.pca if self.use_pca else None,
            'model_type': self.model_type,
            'use_pca': self.use_pca,
            'feature_names': self.feature_names,
            'training_history': self.training_history,
            'saved_at': datetime.now().isoformat()
        }

        with open(filename, 'wb') as f:
            pickle.dump(model_data, f)

        print(f"Модель сохранена в файл: {filename}")

        # Сохранение метрик в JSON
        metrics_file = filename.replace('.pkl', '_metrics.json')
        with open(metrics_file, 'w') as f:
            json.dump({
                'accuracy': self.training_history['accuracy'],
                'roc_auc': self.training_history['roc_auc'],
                'training_time': self.training_history['training_time'],
                'model_type': self.model_type,
                'saved_at': model_data['saved_at']
            }, f, indent=2)

        print(f"Метрики сохранены в: {metrics_file}")

    @classmethod
    def load_model(cls, filename='dog_human_classifier.pkl'):
        """
        Загрузка модели
        """
        import pickle

        with open(filename, 'rb') as f:
            model_data = pickle.load(f)

        # Создание экземпляра
        classifier = cls(
            model_type=model_data['model_type'],
            use_pca=model_data['use_pca']
        )

        # Восстановление состояния
        classifier.model = model_data['model']
        classifier.scaler = model_data['scaler']
        if model_data['use_pca']:
            classifier.pca = model_data['pca']
        classifier.feature_names = model_data['feature_names']
        classifier.training_history = model_data['training_history']

        print(f"Модель загружена из файла: {filename}")
        print(f"Тип модели: {model_data['model_type']}")
        print(f"Точность при обучении: {model_data['training_history']['accuracy']:.2%}")

        return classifier


def compare_models(X_train, X_test, y_train, y_test, feature_names):
    """
    Сравнение нескольких моделей
    """
    print("\n" + "="*60)
    print("СРАВНЕНИЕ МОДЕЛЕЙ")
    print("="*60)

    models_to_test = ['random_forest', 'svm', 'gradient_boosting', 'knn', 'logistic']
    results = {}

    for model_type in models_to_test:
        print(f"\n{'='*40}")
        print(f"Тестирование модели: {model_type.upper()}")
        print(f"{'='*40}")

        # Создание и обучение модели
        classifier = DogHumanClassifier(model_type=model_type, use_pca=True)
        classifier.feature_names = feature_names # Ensure feature names match synthetic data
        classifier.train(X_train, y_train, optimize_hyperparams=True)

        # Оценка
        eval_results = classifier.evaluate(X_test, y_test, verbose=False)

        # Кросс-валидация
        cv_results = classifier.cross_validate(
            np.vstack([X_train, X_test]),
            np.concatenate([y_train, y_test]),
            cv=3
        )

        # Сохранение результатов
        results[model_type] = {
            'classifier': classifier,
            'accuracy': eval_results['accuracy'],
            'roc_auc': eval_results['roc_auc'],
            'cv_mean': cv_results['mean_accuracy'],
            'cv_std': cv_results['std_accuracy'],
            'training_time': classifier.training_history['training_time']
        }

        print(f"  Тестовая точность: {eval_results['accuracy']:.2%}")
        if eval_results['roc_auc']:
            print(f"  Тестовый ROC-AUC: {eval_results['roc_auc']:.2%}")
        print(f"  CV точность: {cv_results['mean_accuracy']:.2%} (±{cv_results['std_accuracy']:.2%})")
        print(f"  Время обучения: {classifier.training_history['training_time']:.2f} сек")

    # Вывод сравнения
    print("\n" + "="*60)
    print("ИТОГОВОЕ СРАВНЕНИЕ")
    print("="*60)

    comparison_df = pd.DataFrame.from_dict(results, orient='index')
    comparison_df = comparison_df.sort_values('accuracy', ascending=False)

    print("\nРейтинг моделей по точности:")
    print(comparison_df[['accuracy', 'roc_auc', 'cv_mean', 'training_time']])

    # Визуализация сравнения
    fig = go.Figure()

    fig.add_trace(go.Bar(
        x=comparison_df.index,
        y=comparison_df['accuracy'],
        name='Точность на тесте',
        marker_color='lightblue'
    ))

    fig.add_trace(go.Bar(
        x=comparison_df.index,
        y=comparison_df['cv_mean'],
        name='CV точность',
        marker_color='lightcoral'
    ))

    fig.update_layout(
        title='Сравнение моделей по точности',
        xaxis_title='Модель',
        yaxis_title='Точность',
        barmode='group',
        template='plotly_white',
        height=500
    )

    return results, comparison_df, fig


def main():
    """
    Основная функция демонстрации
    """
    print("="*60)
    print("КЛАССИФИКАТОР 'СОБАКА VS ЧЕЛОВЕК'")
    print("="*60)

    # 1. Генерация синтетического датасета
    print("\nГенерация синтетического набора данных...")
    n_samples = 1000
    n_features = 29 # Corresponding to the self.feature_names list in the class
    n_informative = 15 # Number of informative features
    n_redundant = 5 # Number of redundant features
    n_repeated = 2 # Number of repeated features
    n_classes = 2 # Binary classification (dog or human)
    random_state = 42

    X, y = make_classification(
        n_samples=n_samples,
        n_features=n_features,
        n_informative=n_informative,
        n_redundant=n_redundant,
        n_repeated=n_repeated,
        n_classes=n_classes,
        random_state=random_state
    )

    # 2. Разделение данных на обучающую и тестовую выборки
    print("Разделение данных на обучающую и тестовую выборки...")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=random_state, stratify=y
    )

    print(f"Размер обучающей выборки: {X_train.shape[0]}")
    print(f"Размер тестовой выборки: {X_test.shape[0]}")

    # 3. Инициализация, обучение и оценка DogHumanClassifier (Random Forest как пример)
    print("\n" + "="*60)
    print("ОБУЧЕНИЕ И ОЦЕНКА ОДНОЙ МОДЕЛИ (RANDOM FOREST)")
    print("="*60)

    rf_classifier = DogHumanClassifier(model_type='random_forest', use_pca=True)
    rf_classifier.feature_names = [f'feature_{i}' for i in range(n_features)] # Ensure feature names match synthetic data
    rf_classifier.train(X_train, y_train, optimize_hyperparams=True)
    evaluation_results = rf_classifier.evaluate(X_test, y_test, verbose=True)

    # 4. Визуализация результатов
    print("\nВизуализация результатов...")
    fig = rf_classifier.visualize_results(X_test, y_test, evaluation_results)
    fig.show()

    # 5. Кросс-валидация
    cv_results = rf_classifier.cross_validate(X, y, cv=5)

    # 6. Сравнение нескольких моделей
    print("\n" + "="*60)
    print("СРАВНЕНИЕ НЕСКОЛЬКИХ МОДЕЛЕЙ")
    print("="*60)

    # For comparison, we use the raw data X, y.
    # The compare_models function will handle splitting internally for CV,
    # but for overall comparison, it needs the full dataset.
    # We pass the feature_names from the first classifier instance.
    all_results, comparison_df, comparison_fig = compare_models(
        X_train, X_test, y_train, y_test, rf_classifier.feature_names
    )
    comparison_fig.show()

    # 7. Сохранение лучшей модели (пример)
    best_model_type = comparison_df.index[0]
    best_classifier = all_results[best_model_type]['classifier']
    best_classifier.save_model(f'best_dog_human_classifier_{best_model_type}.pkl')

    print(f"\nЛучшая модель ({best_model_type}) сохранена.")

main()